### ISSUE TITLE
Feature: Metadata Update (Key Rotation)

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf#23]
Implement the Key Rotation process for offline Keys (Root, Targets, and BIN roles)
Implement Key Rotation for online Keys (BINS, Snapshot, and Timestamp roles)

**Comment by kairoaraujo** [comment]
To implement the key rotation, we have some required issues done before. To avoid blockers and big change
These issues are:
- #28 
- #207
- #208

**Comment by kairoaraujo** [comment]
After a refinement discussion with @MVrachev and @lukpueh, these are the tasks to complete this feature:

- [ ] https://github.com/vmware/repository-service-tuf-worker/issues/221
- [ ] https://github.com/vmware/repository-service-tuf-api/issues/288
- [ ] https://github.com/vmware/repository-service-tuf-cli/issues/221
- [ ] https://github.com/vmware/repository-service-tuf-api/issues/289
- [ ] https://github.com/vmware/repository-service-tuf-cli/issues/222
