### ISSUE TITLE
Feature: Refactoring Authentication/Authorization as a API service

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf#41]
The current API Service has a simple built-in feature: the Authentication/Authorization and the Berear Token/Scope.
TRS scope is not authentication/authorization. Besides, it is implemented in the API to help small deployments.

In a large/complex/enterprise deployment, the System Administrator might want to use an existing authentication tool (example: LDAP, Active Directory, third-part-authentication, etc.) and a specific Authorization for API, such as an API Gateway, etc.

Even if there is a workaround (giving an admin a long-expiration token), it is not ideal for security. For example, if this token is exposed, the steps to fix it are not perfect.

**Comment by kairoaraujo** [comment]
Looks like @kapsalis has an idea for this issue.

**Comment by kapsalis** [comment]
Hi @kairoaraujo . Indeed this is a [draft PR](https://github.com/kapsalis/repository-service-tuf-api/pull/1/files)  on my fork. I am going to add more details tonight and create a draft PR here. It is still draft, because tests fail

**Comment by kapsalis** [comment]
Hi @kairoaraujo , you can find a new draft PR [here](https://github.com/vmware/repository-service-tuf-api/pull/265). In the description, I explain the logic behind the change.

There is one failing test, because of mocking issues. I have to work on a `TestAuthenticationService` to replace the `CustomAuthenticationService` on the test environment, as it is not needed for testing the API and business logic. However, we must add seperate tests at the `CustomAuthenticationService` level

**Comment by kairoaraujo** [comment]
There was a good discussion about this issue in the @kapsalis [PR](https://github.com/vmware/repository-service-tuf-api/pull/265) (draft at the moment of this comment).

To summarize:
* The RSTUF best practices will recommend disabling the built-in RSTUF API and using they own solution (i.e.: API Gateway or direct integration to a Distributed System that offers Authentication/Authorization)

```mermaid
C4Context
      title RSTUF API using external Authentication/Authorization
      Boundary(b0, "Public Environment") {
        Person(system_integration, "CI/CD or Distribution Platform", "Automated Integration")
        Person(rstuf_admin, "RSTUF Admin")
        Person_Ext(rstuf_user, "Developer", "PEP 480")

        System(api_gateway, "API Gateway", "API Gateway SaaS | Container | Server API Gateway")

        Enterprise_Boundary(b1, "Organization Environment") {
          System_Boundary(b2, "RSTUF Deployment") {
            System(rstuf_api_admin, "RSTUF API", "/api/v1/bootstrap | /api/v1/config | /api/v1/key_rotation")
            System(rstuf_api_general, "RSTUF API", "/api/v1/targets | /api/v1/tasks")
          }

          Boundary(b3, "Organization Auth", "Auth/RBAC") {
            System(auth, "User Auth Service")
          }
        }
      }

      Rel(system_integration, api_gateway, "Uses")
      Rel(rstuf_admin, api_gateway, "Uses")
      Rel(rstuf_user, api_gateway, "Uses")
      Rel(api_gateway, rstuf_api_admin, "")
      Rel(api_gateway, rstuf_api_general, "")
      Rel(api_gateway, auth, "")


      UpdateElementStyle(system_integration, $fontColor="red", $bgColor="grey", $borderColor="red")
      UpdateRelStyle(system_integration, api_gateway, $textColor="blue", $lineColor="blue", $offsetX="5")
      UpdateRelStyle(rstuf_admin, api_gateway, $textColor="blue", $lineColor="blue", $offsetX="5")
      UpdateRelStyle(rstuf_user, api_gateway, $textColor="blue", $lineColor="blue", $offsetX="5")
      UpdateRelStyle(api_gateway, auth, $textColor="blue", $lineColor="red", $offsetX="1")

      UpdateLayoutConfig($c4ShapeInRow="2", $c4BoundaryInRow="2")
```

* Disabling the built-in RSTUF API Authentication/Authorization automatically disables the token endpoints
* The implementation will detach the authentication and implement it as an internal service (use as a decorator in the endpoint code base implementation)

For more context, check out the [PR](https://github.com/vmware/repository-service-tuf-api/pull/265) (draft at the moment of this comment)

**Comment by kairoaraujo** [comment]
Following the @kapsalis [comment in his PR](https://github.com/vmware/repository-service-tuf-api/pull/265#issuecomment-1442598447)

Let's plan (breakdown) this change about on/of for Authentication & Authorization (auth/auth) as it is getting bigger and has a big impact on our tests.
My plan will be conducted by the [Proposing new features](https://repository-service-tuf.readthedocs.io/en/latest/devel/development.html#proposing-new-features) guide.

We need to think about all our tests. Most of them (if not all) authenticate using the built-in tokens, including our Functional Tests (BDD), including a specific[ test for tokens](https://github.com/vmware/repository-service-tuf/blob/main/tests/features/tokens/generate.feature).
The first decision here:
- Do we need FT tests for tokens as it is a complete API feature only and not cross-components? cc @MVrachev 
- How do the UT and FT tests skip the authentication if it is disabled?

How I see the plan in three tasks
[ ] Implement the on/of in the current code base
[ ] Solve the tests with ways to avoid breaking all tests.
[ ] Implement the new solution proposed or improve the current one (https://github.com/vmware/repository-service-tuf-api/pull/265) --  also breaking down this one in other tasks in a specific feature branch as suggested by our guide.

**Comment by kairoaraujo** [comment]
IMO, Auth/Auth feature is out of the domain/scope of RSTUF (cc @joshuagl ), but I think we want to help the small RSTUF users.

1. Delete the authentication from RSTUF-API and give them a container with simple authentication (almost a simple API Gateway that does authentication/authorization based on our current/new [PR](https://github.com/vmware/repository-service-tuf-api/pull/265) implementation), i.e: RSTUF-AUTH. 

2. Delete the authentication from RSTUF-API and gives the user settings and a guide on how to deploy a container with some configured service (i.e.: [NGNIX with authentication](https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-1/#implement-auth)) 

For (1) and (2), the user will need to deploy and don't expose the RSTUF-API 80 port but instead expose the container (RSTUF-AUTH or another one).
Our tests go to the Rest API without needing auth/auth.

3. Continue with the [PR](https://github.com/vmware/repository-service-tuf-api/pull/265), but implement a way that our current tests can identify if there is authentication or not and skip it. -- I still need to learn how to solve this problem.

**Comment by kapsalis** [comment]
Hi @kairoaraujo ! Thank you for the neat plan. Two quick comments:

1. My suggestion is to first create the internal authentication service. With the proposed implenetation, it will be easily detached to an external service.

2. UTs for the api endpoints will work with auth enabled or disabled, since these endpoints just use the [decorator](https://github.com/vmware/repository-service-tuf-api/pull/265/files#diff-46899a1bf16f7963d4410ecb893ebc4110fa0b46e9d525e1d95f33f1e2094d5eR22)  to check if user is authorized. No token data are used.

The `/token` endpoints can be considered disabled when authentication is disabled. So, the test will check that the status codw is 404.

**Comment by kairoaraujo** [comment]
> Hi @kairoaraujo ! Thank you for the neat plan. Two quick comments:
> 
> 1. My suggestion is to first create the internal authentication service. With the proposed implenetation, it will be easily detached to an external service.
> 2. UTs for the api endpoints will work with auth enabled or disabled, since these endpoints just use the [decorator](https://github.com/vmware/repository-service-tuf-api/pull/265/files#diff-46899a1bf16f7963d4410ecb893ebc4110fa0b46e9d525e1d95f33f1e2094d5eR22)  to check if user is authorized. No token data are used.
> 
> The `/token` endpoints can be considered disabled when authentication is disabled. So, the test will check that the status code is 404.

Thank you, @kapsalis, for making it clear. I have to confess that I didn't go deep enough to understand it.
I'm removing the  _Implement the on/of in the current code base_ from the above comment.

What about the FT [tests that check the Tokens](https://github.com/vmware/repository-service-tuf/blob/a6d02ff9f7783b13579df26a004171a99dcafb57/tests/features/targets/add_targets.feature#LL1-L9C80)? Otherwise, our FT always presumes we have Auth/Auth.

**Comment by kairoaraujo** [comment]
If we break it down, maybe we can include this one :D 
- https://github.com/vmware/repository-service-tuf/issues/30

**Comment by kapsalis** [comment]
Hi @kairoaraujo. I am not sure for the FTs. I think that if we disable auth, they will still pass even if we send the token. However, it looks a bit weird as a test. Probably, we need two different tests in this case. Or, when auth service is detached, we totally remove the tests, as the authentication is not part of the core.

+1 for the revoke token task. I would like to discuss how we can improve the token usage too.

**Comment by kairoaraujo** [comment]
I spoke with @kapsalis and @MVrachev about this feature, and those will be the tasks.

- [ ] https://github.com/vmware/repository-service-tuf-api/issues/281
- [ ] https://github.com/vmware/repository-service-tuf-api/issues/282
- [ ] https://github.com/vmware/repository-service-tuf/issues/267
- [ ] https://github.com/vmware/repository-service-tuf/issues/269
- [ ] https://github.com/vmware/repository-service-tuf-api/issues/283

**Comment by kapsalis** [comment]
@kairoaraujo could you create a feature branch for the repository-service-tuf-api#283? Thank you!

**Comment by kairoaraujo** [comment]
> @kairoaraujo could you create a feature branch for the repository-service-tuf-api#283? Thank you!

I created the [feature/auth-service](https://github.com/vmware/repository-service-tuf-api/tree/feature/auth-service) in the RSTUF API.
Thank you!

**Comment by kairoaraujo** [comment]
Closing this PR as we removed the Authentication/Authorization feature.
- #472 
- https://github.com/repository-service-tuf/repository-service-tuf/issues/491
