### ISSUE TITLE
Rename umbrella project and repository name

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf#58]
Rename the project to 'Repository Service for TUF'
Rename the repository name to repository-service-tuf

Requires also:
- [x] https://github.com/kaprien/tuf-repository-service-api/issues/120
- [x] https://github.com/kaprien/tuf-repository-service-worker/issues/74
- [x] https://github.com/kaprien/tuf-repository-service-cli/issues/75
